sudo: required
services:
  - docker

before_install:
  - docker build -t sunilkrajulapati/docker-react -f Dockerfile.dev .

script:
  - docker run sunilkrajulapati/docker-react npm run test -- --coverage